# Generated by Django 5.1.7 on 2025-06-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('summa', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Абонементы',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Стили',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_name', models.CharField(max_length=255)),
                ('directions', models.TextField()),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=32, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
            ],
            options={
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
