# Generated by Django 5.1.7 on 2025-05-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_name', models.CharField(max_length=255)),
                ('directions', models.TextField()),
                ('about', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Преподаватели',
            },
        ),
    ]
